name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
